version: '3.8'

services:
  db:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: stock_data_db
    volumes:
      - ./create_ticker_table.sql:/create_ticker_table.sql
      - ./copy_data.sql:/copy_data.sql
      - ./init_db.sh:/docker-entrypoint-initdb.d/init_db.sh
      - ./data.csv:/data.csv
    ports:
      - "5432:5432"