version: "3.8"

services:
  db:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: stock_data_db
    volumes:
      - ./db:/docker-entrypoint-initdb.d/
    ports:
      - "5432:5432"

  app:
    build:
      context: .
    container_name: fastapi-app
    environment:
      DB_NAME: stock_data_db
      DB_USERNAME: user
      DB_PASSWORD: password
      DB_HOST: db
      DB_PORT: 5432
    depends_on:
      - db
    ports:
      - "8000:8000"
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]